### ISSUE TITLE
Most pictures' paths are abs or wrong

### ISSUE THREAD

**Issue by tx19980520** [WXM99/ReadNotes#1]
Most picture path is abs or wrong.
like this.
`![image-20190303185530829](/Users/Miao/Library/Mobile Documents/comappleCloudDocs/GitHub/ReadNotes/DB/Chp1 Intro.assets/image-20190303185530829.png)`

**Comment by WXM99** [comment]
Thanks for your feedback!

We are trying to fix those bugs caused by improper references of images. Some address are absolute, while the rest are invalid ones by blanks and dots.

All the directories end by ``.assets`` are generated by [Typora](https://typora.io/), who names the directory the same as the corresponding markdown file, which may contains blanks and dots. You can also launch an issue to them.

If the content do a little benefit to you, leave a star to my repo for witch I'll appreciate.
